FROM --platform=linux/amd64 openmvs/openmvs-ubuntu:latest AS openmvs_source

FROM --platform=linux/amd64 ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    colmap \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libboost-program-options1.74.0 \
    libboost-serialization1.74.0 \
    libboost-filesystem1.74.0 \
    libboost-system1.74.0 \
    libopencv-core4.5d \
    libgoogle-glog0v5 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=openmvs_source /usr/local/bin/OpenMVS/InterfaceCOLMAP /usr/local/bin/
COPY --from=openmvs_source /usr/local/bin/OpenMVS/DensifyPointCloud /usr/local/bin/
COPY --from=openmvs_source /usr/local/bin/OpenMVS/ReconstructMesh /usr/local/bin/
COPY --from=openmvs_source /usr/local/bin/OpenMVS/TextureMesh /usr/local/bin/
COPY --from=openmvs_source /usr/lib/ /usr/local/lib/

RUN pip3 install --no-cache-dir --upgrade pip setuptools wheel

RUN pip3 install --no-cache-dir opencv-python numpy ultralytics

WORKDIR /workspace
COPY . /workspace

CMD ["python3", "test_cameras.py"]